global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'external_server'
    static_configs:
      - targets: ['<EXTERNAL_SERVER_IP>:9100']

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
